name: Docker CD Tags

on:
  push:
    tags:
      - 'v*'

jobs:

  releases-deploy:

    name: Docker Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set env
        run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF#refs/*/}

      - name: Build and Publish Docker Image
        run: |
          docker build . -t zekro/seiteki:$RELEASE_VERSION
          docker login -u zekro -p ${{ secrets.DOCKER_PASSWORD }}
          docker push zekro/seiteki:$RELEASE_VERSION
